"""empty message

Revision ID: 189d337937af
Revises: c645ecfc5869
Create Date: 2023-06-27 21:27:45.365628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189d337937af'
down_revision = 'c645ecfc5869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xuebu_id', sa.Integer(), nullable=True, comment='学部'))
        batch_op.create_foreign_key(None, 'xuebu', ['xuebu_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('xuebu_id')

    # ### end Alembic commands ###
