"""empty message

Revision ID: 26e6ca809cd4
Revises: 76bbba650450
Create Date: 2023-06-28 15:01:26.985801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e6ca809cd4'
down_revision = '76bbba650450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_office', sa.Integer(), nullable=True, comment='是否机关部门/科室 是：1 不是：0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_column('is_office')

    # ### end Alembic commands ###
