"""empty message

Revision ID: 76bbba650450
Revises: 8f2a69153d7f
Create Date: 2023-06-28 09:52:27.721056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bbba650450'
down_revision = '8f2a69153d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_committee_member', sa.Integer(), nullable=True, comment='是否是中心其他常委'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_committee_member')

    # ### end Alembic commands ###
