"""empty message

Revision ID: 8f2a69153d7f
Revises: 189d337937af
Create Date: 2023-06-28 09:36:33.197629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2a69153d7f'
down_revision = '189d337937af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True, comment='办公室所在部门：医疗办所属部门为卫勤部'))
        batch_op.add_column(sa.Column('xuebu_id', sa.Integer(), nullable=True, comment='学部'))
        batch_op.create_foreign_key(None, 'xuebu', ['xuebu_id'], ['id'])
        batch_op.create_foreign_key(None, 'section', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('xuebu_id')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
