"""empty message

Revision ID: 9f52d6a1eff1
Revises: 
Create Date: 2023-06-17 15:14:13.880080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f52d6a1eff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apply', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apply', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='是否审批通过.有多个审批人时,全部审批完,才为True'))

    # ### end Alembic commands ###
