"""empty message

Revision ID: c645ecfc5869
Revises: 3638d25e464a
Create Date: 2023-06-27 20:08:04.742013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c645ecfc5869'
down_revision = '3638d25e464a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True, comment='片区'))
        batch_op.create_foreign_key(None, 'area', ['area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
